
server:
  port: 8899
  
#eureka:
#  instance:
#    metadataMap:
#      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
#    hostname: ${vcap.application.uris[0]:localhost}
#    nonSecurePort: 80


 #security:
  #basic:
   # enabled: true
    

spring:
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: msateesh889@gmail.com	
    password: Amma@143
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



# Logging the details 
#logging:
 # file: EDPmailService.log
