server:
 port: 5052
 
 #eureka:
 # instance:
 #   metadataMap:
 #     instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
 #   hostname: ${vcap.application.uris[0]:localhost}
 #   nonSecurePort: 80

spring:
  data:
   rest:
    base-path: login
  jpa:
    hibernate:
     ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/emp?useSSL=false
    username: root
    password: Vedams@123

logging:
 level:
  org:
   springframework:
    web: DEBUG
    security: DEBUG
